version: 2
run:
  timeout: 5m
linters:
  disable-all: true
  enable:
    - bodyclose
    - dupl
    - errcheck
    - gocritic
    - gocyclo
    - godot
    - govet
    - ineffassign
    - unused
  disable:
    - staticcheck
  fast: false
linters-settings:
  testpackage:
    skip-regexp: ".*"
  gocyclo:
    min-complexity: 20
  revive:
    rules:
      - name: package-comments
        disabled: true
  mnd:
    checks:
      - argument
      - condition
    ignored-numbers: ['0', '1', '2', '3']
issues:
  exclude-use-default: false
  exclude-dirs-use-default: true
