version: "2"

run:
  timeout: 5m

formatters:
  enable:
    - gofmt
    - goimports
    - gofumpt
  settings:
    gofmt:
      simplify: true

linters:
  enable:
    - bodyclose
    - dupl
    - errcheck
    - gocritic
    - gocyclo
    - godot
    - govet
    - ineffassign
    - unused
    - revive
    - mnd
    - prealloc
    - unparam
    - staticcheck
  settings:
    testpackage:
      skip-regexp: ".*"
    gocyclo:
      min-complexity: 20
    revive:
      rules:
        - name: package-comments
          disabled: true
    mnd:
      checks:
        - argument
        - condition
      ignored-numbers: ["0", "1", "2", "3"]

issues:
  max-same-issues: 0
  max-issues-per-linter: 0
